// Generates the samples shared by Lua and the future TypeScript sonar timeline.
//
// This is a parity fixture, not an independent proof of the Lua formula: it runs the
// Lua implementation and pins the TypeScript port to those results. Behavioural proof
// belongs in tests/encounter_sonar.test.lua.

import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const resourceRoot = resolve(__dirname, '..');
const require = createRequire(import.meta.url);
const { LuaFactory } = require('wasmoon');

const profiles = [
    { k: -0.4, holdRatio: 0.00 },
    { k:  0.5, holdRatio: 0.00 },
    { k: -0.3, holdRatio: 0.35 },
    { k:  0.0, holdRatio: 0.00 },
];
const durations = [4000, 3200, 2400];
const dirs = [1, -1];

const factory = new LuaFactory();
await factory.mountFile('shared/util.lua', readFileSync(join(resourceRoot, 'shared/util.lua'), 'utf8'));
await factory.mountFile('server/encounter_sonar.lua',
    readFileSync(join(resourceRoot, 'server/encounter_sonar.lua'), 'utf8'));
const lua = await factory.createEngine();

try {
    await lua.doString(`
        Encounter = { Register = function() end }
        ZUtil = { clamp = function(value, low, high)
            if value < low then return low end
            if value > high then return high end
            return value
        end }
    `);
    await lua.doFile('server/encounter_sonar.lua');
    await lua.doString(`
        function __sonarWeak(duration, hold, k, dir, t)
            return Sonar.WeakAt({ duration = duration, hold = hold, k = k, dir = dir }, t)
        end
    `);

    const samples = [];
    for (const profile of profiles) {
        for (const dir of dirs) {
            for (const duration of durations) {
                const hold = Math.floor(duration * profile.holdRatio);
                for (let i = 0; i <= 20; i += 1) {
                    const t = Math.round(duration * i / 20);
                    const raw = await lua.global.call('__sonarWeak', duration, hold, profile.k, dir, t);
                    samples.push({
                        duration, hold, k: profile.k, dir, t,
                        pos: Math.round(Number(raw[0]) * 1_000_000) / 1_000_000,
                    });
                }
            }
        }
    }

    const luaRows = samples.map((s) =>
        `    { duration = ${s.duration}, hold = ${s.hold}, k = ${s.k}, dir = ${s.dir}, t = ${s.t}, pos = ${s.pos} },`
    );
    const luaOutput = [
        '-- GENERATED by tests/gen_sonar_fixture.mjs -- do not edit by hand.',
        '-- Regenerate with: node tests/gen_sonar_fixture.mjs',
        '--',
        '-- Sampled from server/encounter_sonar.lua\'s Sonar.WeakAt. This pins the TypeScript',
        '-- implementation to Lua and detects drift. It does NOT prove either formula correct;',
        '-- tests/encounter_sonar.test.lua does that.',
        'SONAR_FIXTURE = {',
        ...luaRows,
        '}',
        '',
    ].join('\n');

    const fixtureDir = join(resourceRoot, 'web', 'src', 'engine', '__fixtures__');
    mkdirSync(fixtureDir, { recursive: true });
    writeFileSync(join(resourceRoot, 'tests', 'sonar_fixture.lua'), luaOutput, 'utf8');
    writeFileSync(join(fixtureDir, 'sonarTimeline.json'), `${JSON.stringify(samples, null, 2)}\n`, 'utf8');
    console.log(`generated ${samples.length} sonar timeline samples`);
} finally {
    lua.global.close();
}
